services:
  backup:
    build: .
    container_name: backup
    restart: always
    networks:
      - misskey_internal_network
    env_file:
      - ./config/.env
    volumes:
      - /opt/misskey-backup/backups:/opt/misskey-backup/backups

networks:
  misskey_internal_network:
    external: true
    name: misskey_internal_network