services:
  backup:
    build: .
    container_name: backup
    restart: always
    networks:
      - misskey_internal_network
      - external_network
    env_file:
      - ./config/.env
    volumes:
      - /opt/misskey-backup/backups:/opt/misskey-backup/backups
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/log/cron.log && grep -q 'Backup succeeded' /var/log/cron.log"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  misskey_internal_network:
    external: true
    name: misskey_internal_network
  external_network:
    driver: bridge