services:
  backup:
    build: .
    container_name: misskey-backup
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - TZ=Asia/Tokyo
    networks:
      - backup_network
      - external_network
    env_file:
      - ./config/.env
    volumes:
      - /opt/misskey-backup/backups:/opt/misskey-backup/backups
    healthcheck:
      test: ['CMD-SHELL', 'pgrep cron >/dev/null && (test ! -f /var/log/cron.log || (test -s /var/log/cron.log && ! grep -q "failed" /var/log/cron.log))']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 3m

networks:
  backup_network:
    name: misskey_backup_network
    external: true
  external_network:
    name: external_network
    external: true